### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by bluusun** [FutureSharks/financial-data#4]
Are there any updates planned for 2018-2020 timeframe? Is there an original source to download more data from?

**Comment by FutureSharks** [comment]
Hey @bluusun,
I've updated to readme to show clearly where the data comes from: https://github.com/FutureSharks/financial-data/commit/7ba1d404aa8b0e1c0f71321acebadcbfb9bcca8d

I updated all data from Oanda a few days ago to the latest. That includes all currency pairs and some new commodities also.

All the other data like crypto and things from histdata are still old but feel free to get new data and make a PR 😃
